# Generated by Django 4.0.6 on 2022-09-05 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RunSQL("INSERT INTO events_events (name) VALUES ('Chuva excessiva')"),
        migrations.RunSQL("INSERT INTO events_events (name) VALUES ('Geada')"),
        migrations.RunSQL("INSERT INTO events_events (name) VALUES ('Granizo')"),
        migrations.RunSQL("INSERT INTO events_events (name) VALUES ('Seca')"),
        migrations.RunSQL("INSERT INTO events_events (name) VALUES ('Vendaval')"),
        migrations.RunSQL("INSERT INTO events_events (name) VALUES ('Raio')"),
    ]
