# Generated by Django 4.0.6 on 2022-09-05 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loss_communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=11)),
                ('localization', models.TextField()),
                ('type', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('events', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='events.events')),
            ],
        ),
    ]
